### PR TITLE
Silence build errors

### PR DESCRIPTION
**Pull request by lascic**
Silences Xcode error "Type 'ViewController' does not conform to protocol 'CocoaMQTTDelegate'". I wasn't able to build and run the project as it required two protocol methods that are required but weren't added before. Left them blank within the scope.

Updated readme, pod file and project settings and added missing app icon assets along the way.

### CODE REVIEW

**Comment by maybites** [comment]
@256dpi Hey joel, whats your take on this request?

**Comment by 256dpi** [comment]
Looks good to me!

@maybites Not sure tough if we should merge this on GitHub or in the development branch on GitLab?

@lascic Thanks for the effort! FYI: I think you haven't be able to build the project because cocoapods made a major version upgrade of the CocoaMQTT dependency when you installed them. But it's always good to have things updated! ;)

**Comment by 256dpi** [comment]
Looks good to me!

@maybites Not sure tough if we should merge this on GitHub or in the development branch on GitLab?

@lascic Thanks for the effort! FYI: I think you haven't be able to build the project because cocoapods made a major version upgrade of the CocoaMQTT dependency when you installed them. But it's always good to have things updated! ;)

**Comment by maybites** [comment]
@256dpi I think we can merge it here, and update the gitlab account afterwards. Do you have merge-pull-request approval rights?

**Pull request merged**
